### ISSUE TITLE
一处翻译错误

### ISSUE THREAD

**Issue by BrentHuang** [fanfeilong/cefutil#11]
Network Layer
By default network requests in CEF3 will be handled in a manner transparent to the host application. 

网络层(Network Layer)
默认情况下，CEF3的网络请求会被宿主程序手工处理。

这一段翻译的有问题，原文说的意思是：默认情况下，cef3怎么处理网络请求对宿主程序是透明的。

**Comment by fanfeilong** [comment]
能帮助改进翻译并pr下？

**Comment by BrentHuang** [comment]
好的，麻烦开个权限给我哈~

**Comment by fanfeilong** [comment]
把你加入开发者了，:)
