### ISSUE TITLE
CEFClose文档

### ISSUE THREAD

**Issue by fanfeilong** [fanfeilong/cefutil#12]
@xnightsky 整理CEF的Close文档

**Comment by xnightsky** [comment]
我来说说CEF的关闭流程：

**Comment by xnightsky** [comment]
我来说windows下CEF3.2171的关闭流程，里面会引用一部分官方库的文档和个人的伪代码，为了辅助理解——
以下是截取自cef_life_span_handler.h的头文件文档，所以一部分文档他还是写在头文件里的，根据他的流程，能很快的去梳理相关逻辑
https://bitbucket.org/chromiumembedded/cef/src/d4b462f0bc0d42a81e682990b4c7a5ccad6fc10f/include/cef_life_span_handler.h?at=2171&fileviewer=file-view-default#cef_life_span_handler.h-124
// The CefLifeSpanHandler::OnBeforeClose() method will be called immediately
  // before the browser object is destroyed. The application should only exit
  // after OnBeforeClose() has been called for all existing browsers.
  //
  // If the browser represents a modal window and a custom modal loop
  // implementation was provided in CefLifeSpanHandler::RunModal() this callback
  // should be used to restore the opener window to a usable state.
  //
  // By way of example consider what should happen during window close when the
  // browser is parented to an application-provided top-level OS window.
  // 1.  User clicks the window close button which sends an OS close
  //     notification (e.g. WM_CLOSE on Windows, performClose: on OS-X and
  //     "delete_event" on Linux).
  // 2.  Application's top-level window receives the close notification and:
  //     A. Calls CefBrowserHost::CloseBrowser(false).
  //     B. Cancels the window close.
  // 3.  JavaScript 'onbeforeunload' handler executes and shows the close
  //     confirmation dialog (which can be overridden via
  //     CefJSDialogHandler::OnBeforeUnloadDialog()).
  // 4.  User approves the close.
  // 5.  JavaScript 'onunload' handler executes.
  // 6.  Application's DoClose() handler is called. Application will:
  //     A. Set a flag to indicate that the next close attempt will be allowed.
  //     B. Return false.
  // 7.  CEF sends an OS close notification.
  // 8.  Application's top-level window receives the OS close notification and
  //     allows the window to close based on the flag from #6B.
  // 9.  Browser OS window is destroyed.
  // 10. Application's CefLifeSpanHandler::OnBeforeClose() handler is called and
  //     the browser object is destroyed.
  // 11. Application exits by calling CefQuitMessageLoop() if no other browsers
  //     exist.

pre1 如果你要管理CefBrowser的生命周期，意味者你必须实现相关 CefLifeSpanHandler接口
